# Darukaa Biodiversity Intelligence AI

## Overview

This project is an AI-powered biodiversity intelligence system designed to provide evidence-backed environmental recommendations.

The system analyzes multiple environmental variables including:

- Soil organic carbon
- Rainfall conditions
- Land-use patterns
- Biodiversity indicators
- Deforestation and pollution signals

The objective is to generate scientifically grounded recommendations that improve biodiversity and ecosystem health.

---

## Architecture

User Input
↓
Environmental Context Builder
↓
Knowledge Retrieval Layer
↓
TF-IDF Vector Search
↓
Multi-Metric Reasoning Engine
↓
Evidence-Backed Recommendations

---

## Knowledge Base

The system uses a structured environmental knowledge base containing:

- Soil health information
- Biodiversity indicators
- Climate factors
- Land-use recommendations
- Habitat restoration strategies

Knowledge is retrieved using TF-IDF vectorization and cosine similarity search.

---

## Features

### Conversational Intelligence

The system asks clarifying questions when critical information is missing.

### Multi-Metric Reasoning

Recommendations are generated by considering multiple environmental variables simultaneously.

### Evidence-Based Outputs

Each recommendation includes:

- Action to perform
- Scientific reasoning
- Impacted metrics
- Time horizon
- Evidence source

---

## Local Setup

Install dependencies:

```bash
pip install -r requirements.txt
```

Run the application:

```bash
uvicorn main:app --reload
```

Open:

```
http://127.0.0.1:8000/docs
```

---

## API Endpoint

POST `/recommend`

Example:

```json
{
  "soil_organic_carbon": 0.3,
  "rainfall": "low",
  "land_use": "monoculture wheat",
  "region": "semi-arid"
}
```

---

## Database / Schema

Current implementation uses a structured JSON knowledge base.

Future improvements:

- pgvector
- PostgreSQL
- Embedding-based retrieval
- Research paper ingestion pipeline

---

## CI/CD

Current version supports GitHub-based source control.

Future deployment:

- GitHub Actions
- Docker
- Cloud deployment
